resources:
- name: pcf-pipelines
  type: git
  source:
    uri: ((git_repo)) 
    branch: ((git_branch))
    skip_ssl_verification: true


jobs:
- name: deploy-turbulence
  plan:
  - get: pcf-pipelines
  - task: deploy-turbulence
    file: pipeline-repo/ci/tasks/deploy.yml
    params:
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}
