resources:
  name: vault
  type: curl
  source:
    url: https://releases.hashicorp.com/vault/0.8.1/vault_0.8.1_linux_amd64.zip
    filename: vault.zip

jobs:
- name: deploy 
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: vault
    - get: pivnet-product
      resource: elastic-runtime
      params: {globs: ["*.pivotal"]}

  - task: upload-tile
    file: pcf-pipelines/tasks/upload-tile/task.yml
    params:
      VAULT_ADDR: {{vault_addr}}
      VAULT_TOKEN: {{vault_token}}
      FOUNDATION_NAME: {{foundation_name}}

  - task: deploy 
    file: pcf-pipelines/tasks/install-tile/task.yml
    params:
      VAULT_ADDR: {{vault_addr}}
      VAULT_TOKEN: {{vault_token}}
      FOUNDATION_NAME: {{foundation_name}}
