jobs:
- name: deploy 
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: vault
    - get: pivnet-product
      resource: elastic-runtime
      params: {globs: ["*.pivotal"]}

  - task: upload-tile
    file: pcf-pipelines/tasks/upload-tile/task.yml
    params:
      OPSMAN_URL: ((opsman_uri))
      OPSMAN_USER: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))

  - task: deploy 
    file: pcf-pipelines/tasks/install-tile/task.yml
    params:
      OPSMAN_URL: ((opsman_uri))
      OPSMAN_USER: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      SERVICES_NETWORK_NAME: ((services_network_name))
      SERVICES_NW_AZS: ((services_nw_azs))
      RABBITMQ_ADMIN: ((rabbitmq_admin))
      RABBITMQ_PASSWORD: ((rabbitmq_password))
