---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  PRODUCT_NAME:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOB_AZ:
  DEPLOYMENT_NW_AZS:
  NETWORK_NAME:
  SERVICE_NETWORK_NAME:


inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/config-tile/task.sh
