---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: allomov/cf-cli
    tag: v1.3

run:
  path: pcf-pipelines/tasks/chaos-loris/register-service-broker.sh

inputs:
- name: pcf-pipelines 
