---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: allomov/cf-cli
    tag: "v1.5"

run:
  path: pcf-pipelines/tasks/chaos-loris/run-app-test.sh

inputs:
- name: pcf-pipelines 
- name: simple-victim-app
