---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
  - name: pcf-pipelines
  - name: pivnet-product 

params:
  VAULT_ADDR: 
  VAULT_TOKEN: 
  FOUNDATION_NAME:

run:
  path: pcf-pipelines/tasks/upload-tile/task.sh
