---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
  - name: pcf-pipelines

params:
  VAULT_ADDR: 
  VAULT_TOKEN: 
  FOUNDATION_NAME:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:

run:
  path: pcf-pipelines/tasks/write-secrets-to-vault/task.sh
